### ISSUE TITLE
Header Component Review

### ISSUE THREAD

**Issue by jordanwillis** [awilliamsproductions/tea_cozy#2]
Now that we discussed ways to improve your nav bar component, let's discuss the header component as a whole (e.g. the logo, title and nav bar combined component).

Going back to semantic HTML, headers are great places to make use of the `<header>` element.  Therefore, I would recommend this instead of your `<div class="nav">` since this is exactly what the element was created for.

Also, I it looks like you were trying to using flexbox in your header in order to layout the logo on the far left and the nav bar on the far right, but ended up using a percentage based width instead.

https://github.com/awilliamsproductions/tea_cozy/blob/master/CSS/teacozy.css#L37

This is a perfect situation to let flexbox shine, so I wanted to share how you would achieve the desired behavior using only flexbox (note there are several ways to achieve this type of layout with flebox).  First you would create your flex container and set everything to align vertically and horizontally.  Note that I am creating a single class for the main flex container properties so that it can be re-used throughout the rest of our HTML.

``` css
.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

header {
  position: fixed;
  z-index: 1;
  align-items: center;
  width: 100%;
  height: 69px;
  border-bottom: 1px solid seashell;
  background-color: black;
}
```

Then you can use the `flex-grow` property to tell either the logo or nav bar to consume 100% of the available space, which will result in the other element getting pushed all the way over.

``` css
nav {
  text-align: right;
  flex-grow: 1;
}
```

So if I through it the HTML, we will end up with a very simply flexbox layout that is responsive and looks great!

``` html
<header class="flex-container">
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-tea-cozy-logo.png" />
  <nav>
    <span><a href="#mission">Mission</a></span>
    <span><a href="#store">Featured Tea</a></span>
    <span><a href="#locations">Locations</a></span>
  </nav>
</header>
```
